// src/lib/datosElectorales.ts

export const partidosPorProvincia: Record<string, string[]> = {
  "Buenos Aires": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria", "Frente de Izquierda"],
  "Catamarca": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Chaco": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Chubut": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Ciudad Autónoma de Buenos Aires": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria", "Frente de Izquierda"],
  "Córdoba": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria", "Frente de Izquierda"],
  "Corrientes": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Entre Ríos": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Formosa": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Jujuy": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria", "Frente de Izquierda"],
  "La Pampa": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "La Rioja": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Mendoza": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria", "Frente de Izquierda"],
  "Misiones": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Neuquén": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria", "Frente de Izquierda"],
  "Río Negro": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Salta": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria", "Frente de Izquierda"],
  "San Juan": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "San Luis": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Santa Cruz": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Santa Fe": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria", "Frente de Izquierda"],
  "Santiago del Estero": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Tierra del Fuego": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
  "Tucumán": ["La Libertad Avanza", "Juntos por el Cambio", "Unión por la Patria"],
};

export const provinciasArgentinas: string[] = [
  "Buenos Aires", "Catamarca", "Chaco", "Chubut", "Ciudad Autónoma de Buenos Aires", 
  "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja",
  "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis",
  "Santa Cruz", "Santa Fe", "Santiago del Estero", "Tierra del Fuego", "Tucumán"
];

export const listaDePaises: string[] = [
  "España", "Estados Unidos", "Italia", "Brasil", "Paraguay", "Uruguay", "Chile", 
  "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda",
  "Arabia Saudita", "Argelia", "Armenia", "Australia", "Austria", "Azerbaiyán",
  "Bahamas", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", "Benín",
  "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", 
  "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde",
  "Camboya", "Camerún", "Canadá", "Catar", "Chad", "China", "Chipre", "Colombia",
  "Comoras", "Congo", "Corea del Norte", "Corea del Sur", "Costa de Marfil",
  "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto",
  "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia",
  "Estonia", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón",
  "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guinea",
  "Guinea-Bisáu", "Guinea Ecuatorial", "Guyana", "Haití", "Honduras", "Hungría",
  "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall",
  "Islas Salomón", "Israel", "Jamaica", "Japón", "Jordania", "Kazajistán", "Kenia",
  "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano",
  "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Madagascar",
  "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio",
  "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia",
  "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger",
  "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán",
  "Palaos", "Panamá", "Papúa Nueva Guinea", "Perú", "Polonia", "Portugal",
  "Reino Unido", "República Centroafricana", "República Checa", "República de Macedonia",
  "República Dominicana", "Ruanda", "Rumania", "Rusia", "Samoa", "San Cristóbal y Nieves",
  "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe",
  "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia",
  "Sri Lanka", "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza",
  "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga",
  "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania",
  "Uganda", "Uzbekistán", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Yibuti",
  "Zambia", "Zimbabue", "Otro"
].sort();